- name: "all | install required packages"
  apt:
    pkg:
      - repmgr
      - python3-psycopg2
      - rsync
    state: present

- name: "all | template /etc/repmgr.conf"
  template:
    src: templates/etc/repmgr.conf.j2
    dest: /etc/repmgr.conf
    owner: root
    group: postgres
    mode: 0640

- name: "primary | create postgresql user repmgr"
  when: repmgr_primary
  postgresql_user:
    name: repmgr
    password: "{{ repmgr_db_password }}"
    role_attr_flags: SUPERUSER
    state: present
  become: True
  become_user: postgres

- name: "primary | create postgresql database repmgr"
  when: repmgr_primary
  postgresql_db:
    name: repmgr
    owner: repmgr
    state: present
  become: True
  become_user: postgres
